live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5c5c5c"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#a6bc69"
magenta = "#c594c5"
red = "#e57373"
white = "#f3f4f5"
yellow = "#fac863"

[colors.cursor]
cursor = "#73D216"
text = "#1F202C"

[colors.normal]
black = "#212121"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#a6bc69"
magenta = "#c594c5"
red = "#e57373"
white = "#c0c5ce"
yellow = "#fac863"

[colors.primary]
background = "#1F202C"
bright_foreground = "#f3f4f5"
foreground = "#73D216"

[cursor]
style = "Block"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[debug]
log_level = "INFO"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "Monospace"
style = "Bold"

[font.bold_italic]
family = "Monospace"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Monospace"
style = "Italic"

[font.normal]
family = "Monospace"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = "Key1"
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = "Key2"
mods = "Alt"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

#[mouse.double_click]
#threshold = 300

#[mouse.triple_click]
#threshold = 300

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "None"
startup_mode = "Windowed"
opacity = 0.90

[window.dimensions]
columns = 130
lines = 40
